import './sass/main.scss'
import './js/container'
import './js/infoFilm'
import './js/modal'
import './js/btnAddRemov'
import './sass/main.scss';
import './js/container';
import './js/headerSwitcher';
import './js/searchFilm';
import './js/themeswitcher';
import './js/teamModal'
