import './sass/main.scss';
import './js/container';
import './js/infoFilm';
import './js/modal';
import './sass/main.scss';
import './js/container';
import './js/headerSwitcher';
import './js/search-film';
import './js/localStorageMovies';
import './js/localStorageExport'
import './js/themeswitcher';
import './js/renderModal';
import './js/up2top';
